import { APIS_TARGET_TYPE_ENUM } from '@/constants/apis';

export const DEFAULT_CALC_CHILDREN_COUNT_TYPES = [
  APIS_TARGET_TYPE_ENUM.FOLDER,
  APIS_TARGET_TYPE_ENUM.SOCKET,
  APIS_TARGET_TYPE_ENUM.API_SAMPLE_GROUP,
];