import i18next from 'i18next';
import _, { uniqBy } from 'lodash';

const createDependencyProposals = function (monaco: any, range: any) {
  const menus = uniqBy(
    [
      {
        label: 'console.log',
        kind: monaco.languages.CompletionItemKind.Function,
        documentation: i18next.t('supplement.print_logs'),
        insertText: 'console.log()',
        range,
      },
      {
        label: 'console.warn',
        kind: monaco.languages.CompletionItemKind.Function,
        documentation: i18next.t('supplement.print_warn'),
        insertText: 'console.log()',
        range,
      },
      {
        label: 'console.info',
        kind: monaco.languages.CompletionItemKind.Function,
        documentation: i18next.t('supplement.print_info'),
        insertText: 'console.error()',
        range,
      },
      {
        label: 'console.error',
        kind: monaco.languages.CompletionItemKind.Function,
        documentation: i18next.t('supplement.print_error'),
        insertText: 'console.error()',
        range,
      },
      {
        label: 'request',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: i18next.t('supplement.cur_req_obj'),
        insertText: 'request',
        range,
      },
      {
        label: 'request.url',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_req_url'),
        insertText: 'request.url',
        range,
      },
      {
        label: 'request.method',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_req_method'),
        insertText: 'request.method',
        range,
      },
      {
        label: 'request.timeout',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_req_timeout'),
        insertText: 'request.timeout',
        range,
      },
      {
        label: 'request.contentType',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_req_type'),
        insertText: 'request.contentType',
        range,
      },
      {
        label: 'request.request_bodys',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_req_body'),
        insertText: 'request.request_bodys',
        range,
      },
      {
        label: 'request.request_headers',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_req_header'),
        insertText: 'request.request_headers',
        range,
      },
      {
        label: 'request.request_querys',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_req_query'),
        insertText: 'request.request_querys',
        range,
      },
      {
        label: 'response',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: i18next.t('supplement.cur_res_obj'),
        insertText: 'response',
        range,
      },
      {
        label: 'response.json',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_res_json'),
        insertText: 'response.json',
        range,
      },
      {
        label: 'response.headers',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_res_header'),
        insertText: 'response.headers',
        range,
      },
      {
        label: 'response.cookies',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_res_cookie'),
        insertText: 'response.cookies',
        range,
      },
      {
        label: 'response.raw',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_res_raw'),
        insertText: 'response.raw',
        range,
      },
      {
        label: 'response.raw.status',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_res_code'),
        insertText: 'response.raw.status',
        range,
      },
      {
        label: 'response.raw.responseTime',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_res_time'),
        insertText: 'response.raw.responseTime',
        range,
      },
      {
        label: 'response.raw.type',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_res_type'),
        insertText: 'response.raw.type',
        range,
      },
      {
        label: 'response.raw.responseText',
        kind: monaco.languages.CompletionItemKind.Field,
        documentation: i18next.t('supplement.cur_res_text'),
        insertText: 'response.raw.responseText',
        range,
      },
      {
        label: 'pm.cookies.get',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: i18next.t('supplement.cur_res_get_cookie'),
        insertText: 'pm.cookies.get',
        range,
      },
      {
        label: 'uuid.v1()',
        kind: monaco.languages.CompletionItemKind.Function,
        documentation: i18next.t('supplement.get_uuid1'),
        insertText: 'uuid.v1()',
        range,
      },
      {
        label: 'uuid.v4()',
        kind: monaco.languages.CompletionItemKind.Function,
        documentation: i18next.t('supplement.get_uuid4'),
        insertText: 'uuid.v4()',
        range,
      },

      {
        label: 'pm.info',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .info `,
        insertText: 'pm.info',
        range,
      },
      {
        label: 'pm.info',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .info `,
        insertText: 'pm.info',
        range,
      },
      {
        label: 'pm.info.eventName',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .info.eventName `,
        insertText: 'pm.info.eventName',
        range,
      },
      {
        label: 'pm.info.eventName',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .info.eventName `,
        insertText: 'pm.info.eventName',
        range,
      },
      {
        label: 'pm.info.iteration',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .info.iteration `,
        insertText: 'pm.info.iteration',
        range,
      },
      {
        label: 'pm.info.iteration',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .info.iteration `,
        insertText: 'pm.info.iteration',
        range,
      },
      {
        label: 'pm.info.iterationCount',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .info.iterationCount `,
        insertText: 'pm.info.iterationCount',
        range,
      },
      {
        label: 'pm.info.iterationCount',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .info.iterationCount `,
        insertText: 'pm.info.iterationCount',
        range,
      },
      {
        label: 'pm.info.requestId',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .info.requestId `,
        insertText: 'pm.info.requestId',
        range,
      },
      {
        label: 'pm.info.requestId',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .info.requestId `,
        insertText: 'pm.info.requestId',
        range,
      },
      {
        label: 'pm.variables',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .variables `,
        insertText: 'pm.variables',
        range,
      },
      {
        label: 'pm.variables',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .variables `,
        insertText: 'pm.variables',
        range,
      },
      {
        label: 'pm.variables.has',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .variables.has `,
        insertText: 'pm.variables.has',
        range,
      },
      {
        label: 'pm.variables.has',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .variables.has `,
        insertText: 'pm.variables.has',
        range,
      },
      {
        label: 'pm.variables.get',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .variables.get `,
        insertText: 'pm.variables.get',
        range,
      },
      {
        label: 'pm.variables.get',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .variables.get `,
        insertText: 'pm.variables.get',
        range,
      },
      {
        label: 'pm.variables.set',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .variables.set `,
        insertText: 'pm.variables.set',
        range,
      },
      {
        label: 'pm.variables.set',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .variables.set `,
        insertText: 'pm.variables.set',
        range,
      },
      {
        label: 'pm.variables.replaceIn',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .variables.replaceIn `,
        insertText: 'pm.variables.replaceIn',
        range,
      },
      {
        label: 'pm.variables.replaceIn',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .variables.replaceIn `,
        insertText: 'pm.variables.replaceIn',
        range,
      },
      {
        label: 'pm.variables.toObject()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .variables.toObject() `,
        insertText: 'pm.variables.toObject()',
        range,
      },
      {
        label: 'pm.variables.toObject()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .variables.toObject() `,
        insertText: 'pm.variables.toObject()',
        range,
      },
      {
        label: 'pm.iterationData',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .iterationData `,
        insertText: 'pm.iterationData',
        range,
      },
      {
        label: 'pm.iterationData',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .iterationData `,
        insertText: 'pm.iterationData',
        range,
      },
      {
        label: 'pm.iterationData.has',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .iterationData.has `,
        insertText: 'pm.iterationData.has',
        range,
      },
      {
        label: 'pm.iterationData.has',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .iterationData.has `,
        insertText: 'pm.iterationData.has',
        range,
      },
      {
        label: 'pm.iterationData.get',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .iterationData.get `,
        insertText: 'pm.iterationData.get',
        range,
      },
      {
        label: 'pm.iterationData.get',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .iterationData.get `,
        insertText: 'pm.iterationData.get',
        range,
      },
      {
        label: 'pm.iterationData.replaceIn',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .iterationData.replaceIn `,
        insertText: 'pm.iterationData.replaceIn',
        range,
      },
      {
        label: 'pm.iterationData.replaceIn',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .iterationData.replaceIn `,
        insertText: 'pm.iterationData.replaceIn',
        range,
      },
      {
        label: 'pm.iterationData.toObject()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .iterationData.toObject() `,
        insertText: 'pm.iterationData.toObject()',
        range,
      },
      {
        label: 'pm.iterationData.toObject()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .iterationData.toObject() `,
        insertText: 'pm.iterationData.toObject()',
        range,
      },
      {
        label: 'pm.environment',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment `,
        insertText: 'pm.environment',
        range,
      },
      {
        label: 'pm.environment',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment `,
        insertText: 'pm.environment',
        range,
      },
      {
        label: 'pm.environment.name',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.name `,
        insertText: 'pm.environment.name',
        range,
      },
      {
        label: 'pm.environment.name',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.name `,
        insertText: 'pm.environment.name',
        range,
      },
      {
        label: 'pm.environment.values',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.values `,
        insertText: 'pm.environment.values',
        range,
      },
      {
        label: 'pm.environment.values',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.values `,
        insertText: 'pm.environment.values',
        range,
      },
      {
        label: 'pm.environment.has',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.has `,
        insertText: 'pm.environment.has',
        range,
      },
      {
        label: 'pm.environment.has',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.has `,
        insertText: 'pm.environment.has',
        range,
      },
      {
        label: 'pm.environment.get',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.get `,
        insertText: 'pm.environment.get',
        range,
      },
      {
        label: 'pm.environment.get',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.get `,
        insertText: 'pm.environment.get',
        range,
      },
      {
        label: 'pm.environment.set',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.set `,
        insertText: 'pm.environment.set',
        range,
      },
      {
        label: 'pm.environment.set',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.set `,
        insertText: 'pm.environment.set',
        range,
      },
      {
        label: 'pm.environment.replaceIn',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.replaceIn `,
        insertText: 'pm.environment.replaceIn',
        range,
      },
      {
        label: 'pm.environment.replaceIn',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.replaceIn `,
        insertText: 'pm.environment.replaceIn',
        range,
      },
      {
        label: 'pm.environment.toObject()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.toObject() `,
        insertText: 'pm.environment.toObject()',
        range,
      },
      {
        label: 'pm.environment.toObject()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.toObject() `,
        insertText: 'pm.environment.toObject()',
        range,
      },
      {
        label: 'pm.environment.getName()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.getName() `,
        insertText: 'pm.environment.getName()',
        range,
      },
      {
        label: 'pm.environment.getName()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.getName() `,
        insertText: 'pm.environment.getName()',
        range,
      },
      {
        label: 'pm.environment.getPreUrl()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.getPreUrl() `,
        insertText: 'pm.environment.getPreUrl()',
        range,
      },
      {
        label: 'pm.environment.getPreUrl()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.getPreUrl() `,
        insertText: 'pm.environment.getPreUrl()',
        range,
      },
      {
        label: 'pm.environment.getCollection()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.getCollection() `,
        insertText: 'pm.environment.getCollection()',
        range,
      },
      {
        label: 'pm.environment.getCollection()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.getCollection() `,
        insertText: 'pm.environment.getCollection()',
        range,
      },
      {
        label: 'pm.environment.unset',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.unset `,
        insertText: 'pm.environment.unset',
        range,
      },
      {
        label: 'pm.environment.unset',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.unset `,
        insertText: 'pm.environment.unset',
        range,
      },
      {
        label: 'pm.environment.clear()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.clear() `,
        insertText: 'pm.environment.clear()',
        range,
      },
      {
        label: 'pm.environment.clear()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .environment.clear() `,
        insertText: 'pm.environment.clear()',
        range,
      },
      {
        label: 'pm.globals',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals `,
        insertText: 'pm.globals',
        range,
      },
      {
        label: 'pm.globals',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals `,
        insertText: 'pm.globals',
        range,
      },
      {
        label: 'pm.globals.has',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.has `,
        insertText: 'pm.globals.has',
        range,
      },
      {
        label: 'pm.globals.has',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.has `,
        insertText: 'pm.globals.has',
        range,
      },
      {
        label: 'pm.globals.get',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.get `,
        insertText: 'pm.globals.get',
        range,
      },
      {
        label: 'pm.globals.get',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.get `,
        insertText: 'pm.globals.get',
        range,
      },
      {
        label: 'pm.globals.set',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.set `,
        insertText: 'pm.globals.set',
        range,
      },
      {
        label: 'pm.globals.set',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.set `,
        insertText: 'pm.globals.set',
        range,
      },
      {
        label: 'pm.globals.replaceIn',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.replaceIn `,
        insertText: 'pm.globals.replaceIn',
        range,
      },
      {
        label: 'pm.globals.replaceIn',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.replaceIn `,
        insertText: 'pm.globals.replaceIn',
        range,
      },
      {
        label: 'pm.globals.toObject()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.toObject() `,
        insertText: 'pm.globals.toObject()',
        range,
      },
      {
        label: 'pm.globals.toObject()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.toObject() `,
        insertText: 'pm.globals.toObject()',
        range,
      },
      {
        label: 'pm.globals.unset',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.unset `,
        insertText: 'pm.globals.unset',
        range,
      },
      {
        label: 'pm.globals.unset',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.unset `,
        insertText: 'pm.globals.unset',
        range,
      },
      {
        label: 'pm.globals.clear()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.clear() `,
        insertText: 'pm.globals.clear()',
        range,
      },
      {
        label: 'pm.globals.clear()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .globals.clear() `,
        insertText: 'pm.globals.clear()',
        range,
      },
      {
        label: 'pm.cookies',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .cookies `,
        insertText: 'pm.cookies',
        range,
      },
      {
        label: 'pm.cookies',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .cookies `,
        insertText: 'pm.cookies',
        range,
      },
      {
        label: 'pm.cookies.has',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .cookies.has `,
        insertText: 'pm.cookies.has',
        range,
      },
      {
        label: 'pm.cookies.has',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .cookies.has `,
        insertText: 'pm.cookies.has',
        range,
      },
      {
        label: 'pm.cookies.get',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .cookies.get `,
        insertText: 'pm.cookies.get',
        range,
      },
      {
        label: 'pm.cookies.get',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .cookies.get `,
        insertText: 'pm.cookies.get',
        range,
      },
      {
        label: 'pm.cookies.toObject()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .cookies.toObject() `,
        insertText: 'pm.cookies.toObject()',
        range,
      },
      {
        label: 'pm.cookies.toObject()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .cookies.toObject() `,
        insertText: 'pm.cookies.toObject()',
        range,
      },
      {
        label: 'pm.cookies.jar()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .cookies.jar() `,
        insertText: 'pm.cookies.jar()',
        range,
      },
      {
        label: 'pm.cookies.jar()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .cookies.jar() `,
        insertText: 'pm.cookies.jar()',
        range,
      },
      {
        label: 'pm.test',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .test `,
        insertText: 'pm.test',
        range,
      },
      {
        label: 'pm.test',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .test `,
        insertText: 'pm.test',
        range,
      },
      {
        label: 'pm.expect',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .expect `,
        insertText: 'pm.expect',
        range,
      },
      {
        label: 'pm.expect',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .expect `,
        insertText: 'pm.expect',
        range,
      },
      // {
      //     "label": "pm.sendRequest",
      //     "kind": monaco.languages.CompletionItemKind.Method,
      //     "documentation": `EchoAPI ${i18next.t('supplement.builtin')} .sendRequest ",
      //     "insertText": "pm.sendRequest",
      //     range
      // },
      // {
      //     "label": "pm.sendRequest",
      //     "kind": monaco.languages.CompletionItemKind.Method,
      //     "documentation": `EchoAPI ${i18next.t('supplement.builtin')} .sendRequest ",
      //     "insertText": "pm.sendRequest",
      //     range
      // },
      {
        label: 'pm.setRequestHeader',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .setRequestHeader `,
        insertText: 'pm.setRequestHeader',
        range,
      },
      {
        label: 'pm.setRequestHeader',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .setRequestHeader `,
        insertText: 'pm.setRequestHeader',
        range,
      },
      {
        label: 'pm.removeRequestHeader',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .removeRequestHeader `,
        insertText: 'pm.removeRequestHeader',
        range,
      },
      {
        label: 'pm.removeRequestHeader',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .removeRequestHeader `,
        insertText: 'pm.removeRequestHeader',
        range,
      },
      {
        label: 'pm.setRequestQuery',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .setRequestQuery `,
        insertText: 'pm.setRequestQuery',
        range,
      },
      {
        label: 'pm.setRequestQuery',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .setRequestQuery `,
        insertText: 'pm.setRequestQuery',
        range,
      },
      {
        label: 'pm.removeRequestQuery',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .removeRequestQuery `,
        insertText: 'pm.removeRequestQuery',
        range,
      },
      {
        label: 'pm.removeRequestQuery',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .removeRequestQuery `,
        insertText: 'pm.removeRequestQuery',
        range,
      },
      {
        label: 'pm.setRequestBody',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .setRequestBody `,
        insertText: 'pm.setRequestBody',
        range,
      },
      {
        label: 'pm.setRequestBody',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .setRequestBody `,
        insertText: 'pm.setRequestBody',
        range,
      },
      {
        label: 'pm.removeRequestBody',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .removeRequestBody `,
        insertText: 'pm.removeRequestBody',
        range,
      },
      {
        label: 'pm.removeRequestBody',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .removeRequestBody `,
        insertText: 'pm.removeRequestBody',
        range,
      },
      {
        label: '$.ajax',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} $.ajax `,
        insertText: '$.ajax',
        range,
      },
      {
        label: 'pm.request',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request `,
        insertText: 'pm.request',
        range,
      },
      {
        label: 'pm.request',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request `,
        insertText: 'pm.request',
        range,
      },
      {
        label: 'pm.request.headers',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.headers `,
        insertText: 'pm.request.headers',
        range,
      },
      {
        label: 'pm.request.headers',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.headers `,
        insertText: 'pm.request.headers',
        range,
      },
      {
        label: 'pm.request.headers.add',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.headers.add `,
        insertText: 'pm.request.headers.add',
        range,
      },
      {
        label: 'pm.request.headers.add',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.headers.add `,
        insertText: 'pm.request.headers.add',
        range,
      },
      {
        label: 'pm.request.headers.remove',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.headers.remove `,
        insertText: 'pm.request.headers.remove',
        range,
      },
      {
        label: 'pm.request.headers.remove',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.headers.remove `,
        insertText: 'pm.request.headers.remove',
        range,
      },
      {
        label: 'pm.request.headers.upsert',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.headers.upsert `,
        insertText: 'pm.request.headers.upsert',
        range,
      },
      {
        label: 'pm.request.headers.upsert',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.headers.upsert `,
        insertText: 'pm.request.headers.upsert',
        range,
      },
      {
        label: 'pm.request.method',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.method `,
        insertText: 'pm.request.method',
        range,
      },
      {
        label: 'pm.request.method',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.method `,
        insertText: 'pm.request.method',
        range,
      },
      {
        label: 'pm.request.body',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.body `,
        insertText: 'pm.request.body',
        range,
      },
      {
        label: 'pm.request.body',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.body `,
        insertText: 'pm.request.body',
        range,
      },
      {
        label: 'pm.request.url',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.url `,
        insertText: 'pm.request.url',
        range,
      },
      {
        label: 'pm.request.url',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .request.url `,
        insertText: 'pm.request.url',
        range,
      },
      {
        label: 'pm.response',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response `,
        insertText: 'pm.response',
        range,
      },
      {
        label: 'pm.response',
        kind: monaco.languages.CompletionItemKind.Class,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response `,
        insertText: 'pm.response',
        range,
      },
      {
        label: 'pm.response.code',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.code `,
        insertText: 'pm.response.code',
        range,
      },
      {
        label: 'pm.response.code',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.code `,
        insertText: 'pm.response.code',
        range,
      },
      {
        label: 'pm.response.status',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.status `,
        insertText: 'pm.response.status',
        range,
      },
      {
        label: 'pm.response.status',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.status `,
        insertText: 'pm.response.status',
        range,
      },
      {
        label: 'pm.response.headers',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.headers `,
        insertText: 'pm.response.headers',
        range,
      },
      {
        label: 'pm.response.headers',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.headers `,
        insertText: 'pm.response.headers',
        range,
      },
      {
        label: 'pm.response.responseTime',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.responseTime `,
        insertText: 'pm.response.responseTime',
        range,
      },
      {
        label: 'pm.response.responseTime',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.responseTime `,
        insertText: 'pm.response.responseTime',
        range,
      },
      {
        label: 'pm.response.responseSize',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.responseSize `,
        insertText: 'pm.response.responseSize',
        range,
      },
      {
        label: 'pm.response.responseSize',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.responseSize `,
        insertText: 'pm.response.responseSize',
        range,
      },
      {
        label: 'pm.response.text()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.text() `,
        insertText: 'pm.response.text()',
        range,
      },
      {
        label: 'pm.response.text()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.text() `,
        insertText: 'pm.response.text()',
        range,
      },
      {
        label: 'pm.response.json()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.json() `,
        insertText: 'pm.response.json()',
        range,
      },
      {
        label: 'pm.response.json()',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} .response.json() `,
        insertText: 'pm.response.json()',
        range,
      },
      {
        label: 'postman.setEnvironmentVariable',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} postman.setEnvironmentVariable `,
        insertText: 'postman.setEnvironmentVariable',
        range,
      },
      {
        label: 'postman.getEnvironmentVariable',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} postman.getEnvironmentVariable `,
        insertText: 'postman.getEnvironmentVariable',
        range,
      },
      {
        label: 'postman.clearEnvironmentVariable',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t(
          'supplement.builtin'
        )} postman.clearEnvironmentVariable `,
        insertText: 'postman.clearEnvironmentVariable',
        range,
      },
      {
        label: 'postman.clearEnvironmentVariables',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t(
          'supplement.builtin'
        )} postman.clearEnvironmentVariables `,
        insertText: 'postman.clearEnvironmentVariables',
        range,
      },
      {
        label: 'postman.setGlobalVariable',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} postman.setGlobalVariable `,
        insertText: 'postman.setGlobalVariable',
        range,
      },
      {
        label: 'postman.getGlobalVariable',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} postman.getGlobalVariable `,
        insertText: 'postman.getGlobalVariable',
        range,
      },
      {
        label: 'postman.clearGlobalVariable',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} postman.clearGlobalVariable `,
        insertText: 'postman.clearGlobalVariable',
        range,
      },
      {
        label: 'postman.clearGlobalVariables',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} postman.clearGlobalVariables `,
        insertText: 'postman.clearGlobalVariables',
        range,
      },
      {
        label: 'postman.setNextRequest',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} postman.setNextRequest `,
        insertText: 'postman.setNextRequest',
        range,
      },
      {
        label: 'postman.getResponseCookie',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} postman.getResponseCookie `,
        insertText: 'postman.getResponseCookie',
        range,
      },
      {
        label: 'postman.getResponseHeader',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} postman.getResponseHeader `,
        insertText: 'postman.getResponseHeader',
        range,
      },
      {
        label: 'echoapi.setEnvironmentVariable',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} echoapi.setEnvironmentVariable `,
        insertText: 'echoapi.setEnvironmentVariable',
        range,
      },
      {
        label: 'echoapi.getEnvironmentVariable',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} echoapi.getEnvironmentVariable `,
        insertText: 'echoapi.getEnvironmentVariable',
        range,
      },
      {
        label: 'echoapi.clearEnvironmentVariable',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t(
          'supplement.builtin'
        )} echoapi.clearEnvironmentVariable `,
        insertText: 'echoapi.clearEnvironmentVariable',
        range,
      },
      {
        label: 'echoapi.clearEnvironmentVariables',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t(
          'supplement.builtin'
        )} echoapi.clearEnvironmentVariables `,
        insertText: 'echoapi.clearEnvironmentVariables',
        range,
      },
      {
        label: 'echoapi.setGlobalVariable',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} echoapi.setGlobalVariable `,
        insertText: 'echoapi.setGlobalVariable',
        range,
      },
      {
        label: 'echoapi.getGlobalVariable',
        kind: monaco.languages.CompletionItemKind.Property,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} echoapi.getGlobalVariable `,
        insertText: 'echoapi.getGlobalVariable',
        range,
      },
      {
        label: 'echoapi.clearGlobalVariable',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} echoapi.clearGlobalVariable `,
        insertText: 'echoapi.clearGlobalVariable',
        range,
      },
      {
        label: 'echoapi.clearGlobalVariables',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} echoapi.clearGlobalVariables `,
        insertText: 'echoapi.clearGlobalVariables',
        range,
      },
      {
        label: 'echoapi.setNextRequest',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} echoapi.setNextRequest `,
        insertText: 'echoapi.setNextRequest',
        range,
      },
      {
        label: 'echoapi.getResponseCookie',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} echoapi.getResponseCookie `,
        insertText: 'echoapi.getResponseCookie',
        range,
      },
      {
        label: 'echoapi.getResponseHeader',
        kind: monaco.languages.CompletionItemKind.Method,
        documentation: `EchoAPI ${i18next.t('supplement.builtin')} echoapi.getResponseHeader `,
        insertText: 'echoapi.getResponseHeader',
        range,
      },
    ],
    'label'
  );

  // add lodash quick suggestions
  _.forEach(_.keys(_), function (label) {
    menus.push({
      label: `_.${label}`,
      kind: monaco.languages.CompletionItemKind.Function,
      documentation: i18next.t('supplement.loadsh', { label: label }),
      insertText: `_.${label}`,
      range,
    });
  });

  return menus;
};

export default createDependencyProposals;
