import { GlobalToken } from 'antd/es/theme/interface';

export interface ThemeToken extends GlobalToken {
  colorFontLightHover: string;
  colorBgLightHover: string;
  colorPrimaryOpacity: string;
  searchBigSelectColor: string;
  popoverSelectBgColor: string;
  popoverSelectBgHoverColor: string;
  colorBgGray: string;
  colorDashed: string;
  colorBgPage: string;
  colorBgRight: string;
  colorBgFolder: string;
  headerBgColor: string;
  searchBgColor: string;
  searchBigBgColor: string;
  tableHeaderBgColor: string;
  colorBgFolderHover: string;
  colorDeepGray: string;
  selectHoverColor: string;
  formHoverColor: string;
  dividerColor: string;
  checkBoxBorderColor: string;
  colorBorder: string;
  tableColorBorder:string;
  colorBorderLight: string;
  iconColor: string;
  fontTitleColor: string;
  fontContentColor: string;
  fontLightColor: string;
  borderRadius: number;
  colorPrimary: string;
  iconPrimaryColor: string;
  SelectedBorderColor: string;
  WhiteColor: string;
  colorError: string;
  colorSuccess: string;
  fontSize: number;
  fontSize14: number;
  boxShadowModalColor: string;
  highlightChangeColor: string;
  scrollbarThumbBgColor: string;
  scrollbarThumbHoverBgColor: string;
  colorBgTreePage: string;
  padding8: number;
  padding10: number;
  padding12: number;
  padding14: number;
  padding16: number;
  padding18: number;
  padding20: number;

  margin8: number;
  margin10: number;
  margin12: number;
  margin14: number;
  margin16: number;
  margin18: number;
  margin20: number;
  modalContentBg: string;
  modalMaskBg: string;
  fontSize16: number;
}
