import React, { useEffect, useMemo, useRef } from 'react';
import ReactDOM from 'react-dom';
import { useTranslation } from 'react-i18next';

import { useMemoizedFn, useSafeState } from 'ahooks';
import cn from 'classnames';
import { cloneDeep, find, isFunction, isObject, isPlainObject, isUndefined, map } from 'lodash';
import { useShallow } from 'zustand/react/shallow';

import { SYSTEM_VARS } from '@/constants/system';
import { useProjectConfig } from '@/store';

import { VarMentionsWrap } from './style';

const envVarMarkVarsList = [];

interface EnvVarsProps {
  envVisible?: boolean;
  offset?: any;
  onCancel?: () => void;
  onSelect?: (newVal: string) => void;
  env_id: string;
}

const EnvVar = (props: EnvVarsProps) => {
  const { t } = useTranslation();
  const { envVisible, offset, onCancel, onSelect, env_id = '-1' } = props;
  const { envList, globalVars } = useProjectConfig(
    useShallow(({ envList, globalVars }) => ({
      envList,
      globalVars,
    }))
  );
  // Current environment variables
  const envVars = useMemo(() => {
    return find(envList, (item) => env_id === item?.env_id)?.env_var_list || {};
  }, [envList, env_id]);
  // Current active item index
  const [itemIndex, setItemIndex] = useSafeState(0);
  const [markVarsList, setMarkVarsList] = useSafeState([]);
  const refItemIndex = useRef(0);

  // Global variables generated by scripts
  const global_vars: { [k: string]: string } = useMemo(() => {
    const glb: { [k: string]: string } = {};
    for (const key in globalVars || {}) {
      if (Object.prototype.hasOwnProperty.call(globalVars, key)) {
        const element = globalVars[key];
        glb[key] = element?.current_value || element?.value;
      }
    }
    return glb;
  }, [globalVars]);

  const currentItem: {
    key: string;
    value: string;
    envType: string;
    description: string;
    current_value: string;
  } = markVarsList?.[itemIndex];

  useEffect(() => {
    const template_mock_vars: any = {};
    Object.keys(SYSTEM_VARS).forEach((k) => {
      template_mock_vars[k] = {
        key: `$${k}`,
        value: `$${k}`,
        description: SYSTEM_VARS[k],
      };
    });
    const data = {
      envList: isPlainObject(envVars) ? cloneDeep(envVars) : {},
      gloList: isPlainObject(global_vars) ? cloneDeep(global_vars) : {},
      mockVarsList: template_mock_vars,
    };
    const varsList: any = [];
    Object.values(data).forEach((obj, index) => {
      Object.keys(obj).forEach((k) => {
        try {
          if (index === 1) {
            varsList.push({
              key: k,
              value: obj[k],
              envType: 'global',
              description: obj[k],
            });
          } else if (isObject(obj[k])) {
            if (!obj[k]?.key) {
              obj[k].key = k;
            }
            obj[k].envType = index === 0 ? 'env' : 'global';
            varsList.push(obj[k]);
          }
        } catch (error) {
          // error
        }
      });
    });

    setMarkVarsList(varsList);
  }, [envVars, global_vars, setMarkVarsList]);

  const changeActive = (i: number) => {
    let x = 0;
    if (itemIndex !== null) {
      x = itemIndex + i;
    }
    const varDom: HTMLElement | null = document.getElementById('scroll-env-vars');
    if (i === 1) {
      const isScroll = varDom && varDom.scrollTop + 8 * 28 < (x + 1) * 28;
      if (isScroll) varDom.scrollTop = (x - 7) * 28;
      if (refItemIndex.current >= 0) {
        refItemIndex.current -= 1;
      }
    }
    if (i === -1) {
      if (refItemIndex.current < 7) {
        refItemIndex.current += 1;
      }
      const isScroll =
        (varDom && varDom.scrollTop === (x - 1) * 28) || x === envVarMarkVarsList.length - 8;
      if (isScroll && varDom) {
        varDom.scrollTop = (x - 2) * 28 >= 0 ? (x - 2) * 28 : 0;
      }
    }

    setItemIndex(x);
  };

  const listener = useMemoizedFn((e) => {
    if (e.code === 'ArrowDown') {
      if (itemIndex < markVarsList?.length - 1) changeActive(1);
    }
    if (e.code === 'ArrowUp') {
      if (itemIndex > 0) changeActive(-1);
    }
    if (e.code === 'Enter') {
      const markItem: { key: string; value: string; envType: string; description: string } =
        markVarsList[itemIndex];

      if (!isUndefined(markItem)) {
        if (isFunction(onSelect)) {
          onSelect(markItem.key);
        }
        setTimeout(() => {
          onCancel && onCancel();
        }, 0);
      }
    }
  });

  useEffect(() => {
    document.addEventListener('keydown', listener, true);
    return () => {
      document.removeEventListener('keydown', listener, true);
    };
  }, []);

  const handleSelectMarkItem = useMemoizedFn(
    (value: string, e: React.MouseEvent<HTMLDivElement>) => {
      e.stopPropagation();
      e.preventDefault();
      onSelect && onSelect(value);
      setTimeout(() => {
        onCancel && onCancel();
      }, 0);
    }
  );

  const calcValue = (value: unknown) => {
    if (isObject(value)) {
      return JSON.stringify(value);
    }

    return `${value}`;
  };

  return (
    <>
      {envVisible &&
        currentItem &&
        ReactDOM.createPortal(
          <VarMentionsWrap>
            <div className="related-env-vars" style={offset}>
              <div className="env-vars-list" id="scroll-env-vars">
                {map(markVarsList, (item: any, index) => (
                  <div
                    key={`${item.key} + ${index}`}
                    className={cn('env-vars-default', { active: itemIndex === index })}
                    onFocus={setItemIndex.bind(null, index)}
                    onMouseOver={setItemIndex.bind(null, index)}
                    onMouseDown={handleSelectMarkItem.bind(null, item.key)}
                  >
                    <div
                      className={cn('default-type', {
                        e: item?.envType === 'env',
                      })}
                    >
                      {item?.envType === 'env' ? 'E' : 'G'}
                    </div>
                    <div className="default-name text-ellipse2">{item.key}</div>
                    <div className="default-icon"></div>
                  </div>
                ))}
              </div>
              <div className="env-vars-desc">
                <div className="desc-title">{t('supplement.var_name')}</div>
                <div className="var-name">{currentItem.key}</div>
                <div className="desc-title" style={{ margin: '16px 0 0 0' }}>
                  {t('supplement.var_value')}
                </div>
                <div className="var-value">
                  {calcValue(
                    currentItem?.envType === 'env'
                      ? currentItem?.current_value || currentItem?.value
                      : currentItem.description
                  )}
                </div>
                <div className="desc-title" style={{ margin: '16px 0 0 0' }}>
                  {t('supplement.scope')}
                </div>
                <div className="var-value">
                  {currentItem?.envType === 'env'
                    ? t('supplement.var_env')
                    : t('supplement.var_glo')}
                </div>
              </div>
            </div>
          </VarMentionsWrap>,
          document.querySelector('body') as HTMLElement
        )}
    </>
  );
};

export default EnvVar;
